version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    groups:
      workflows:
        patterns:
          - "*"
  # Maintain dependencies for pyproject.toml - uses pip ecosystem
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    ignore:
      - update-types: ["version-update:semver-patch"]
        dependency-name: "*"
    pull-request-branch-name:
      separator: "-"
    groups:
      python-deps:
        patterns:
          - "*"
  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "-"
    groups:
      base-images:
        patterns:
          - "*"
