exclude: .svg$
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks
  autoupdate_schedule: monthly
  autoupdate_commit_msg: 'chore: update pre-commit hook versions'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: name-tests-test
        args: [--pytest-test-first]
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
